In [1]:
import torch as t
import numpy as np
t.__version__

'0.4.0'

# Base pytorch manipulation

In [2]:
a = [[2,3,0],[1,2,0],[1,0,1]] # list type
b = np.multiply(a,a)
c = np.dot(a,a) # matrix multiply 点乘
d = np.array(a)*np.array(a) # element-wise corresponding multiply 对应相乘
# a*a is wrong
print(b,'\n',c)


[[4 9 0]
 [1 4 0]
 [1 0 1]] 
 [[ 7 12  0]
 [ 4  7  0]
 [ 3  3  1]]


In [3]:
a = t.FloatTensor(a) # create a tensor
b = t.from_numpy(b) # transform from numpy to tensor type
ta = t.mm(a,a) # np.dot(a,a) matrix multiply
# tb = torch.dot(a,a)


In [7]:
b = b.numpy()# transform from tensor to numpy type

In [8]:
b

array([[4, 9, 0],
       [1, 4, 0],
       [1, 0, 1]])

In [49]:
d = t.Tensor(2,2) # create a tensor with a shape of 2*2 without initialization
d

tensor([[-4.3490e+18,  4.5696e-41],
        [ 4.2543e-38,  0.0000e+00]])

In [50]:
d = t.randint(1,9,(1,3,5)) # have an integer random initializationb which requires the grad function
d

tensor([[[ 2.,  7.,  8.,  4.,  2.],
         [ 8.,  4.,  6.,  8.,  7.],
         [ 6.,  3.,  7.,  2.,  4.]]])

In [51]:
print(d.shape)
print(d.size())
print(d.size(2)) # specialize the axis 

torch.Size([1, 3, 5])
torch.Size([1, 3, 5])
5


In [52]:
e = t.randint(1,9,(1,3,5)) # have an integer random initializationb which requires the grad function
print(d+e == t.add(d,e)) # the same method for the sum

tensor([[[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1]]], dtype=torch.uint8)


In [53]:
print(d+e)

tensor([[[  3.,  10.,  16.,  11.,   6.],
         [ 13.,   8.,  11.,  15.,  12.],
         [ 12.,  11.,  15.,   9.,  11.]]])


In [55]:
print(d.add_(e)) # in_place operation which is not suitable for the 'require_grad'

tensor([[[  4.,  13.,  24.,  18.,  10.],
         [ 18.,  12.,  16.,  22.,  17.],
         [ 18.,  19.,  23.,  16.,  18.]]])


In [65]:
# t.tensor is different from t.Tensor,torch.Tensor
#has been splitted into torch.tensor and torch.empty
a = t.tensor([1,2]) # accept list
a = t.tensor(1) # scalar
a = t.Tensor(2,3) # Tensor(only the shape)
a = t.empty(2,3) # be the same
a = a.numpy()

In [140]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [127]:
'''a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1,the end position is ommitted
a[:]         # a copy of the whole array
There is also the step value, which can be used with any of the above:

a[start:end:step] # start through not past end, by step
The key point to remember is that the :end value represents the first value that is not in the selected slice. So, the difference beween end and start is the number of elements selected (if step is 1, the default).

The other feature is that start or end may be a negative number, which means it counts from the end of the array instead of the beginning. So:

a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items
Similarly, step may be a negative number:

a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed'''
print(a[-3::-1])
print(a[:-3:-1])

[9 8 7 6 5 4 3 2 1 0]
[11 10]


In [141]:
a = t.from_numpy(a)
b = a.detach()
print(a,b)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]) tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])


In [143]:
dev = t.device('cuda'if t.cuda.is_available() else 'cpu')
a = a.to(dev)
b = b.to(dev)

In [145]:
a,b

(tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11], device='cuda:0'),
 tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11], device='cuda:0'))

# grad manipulation